tags = {
    "ACREDITACION DE HABERES": "SUELDO",
    "PINCHI": "EXPENSAS",
    "CABLEVISION": "TELECOM",
    "PLAZO FIJO": "INVERSIONES",
    "TELECOM": "TELECOM",
    "PAGO TARJETA CREDITO": "TARJETA",
    "EXTRACCION": "EFECTIVO",
    "CULTURAL PUEBLO": "COLEGIO",
    "METROGAS": "METROGAS",
    "INM/ABL": "ABL",
    "LOMAS DE NUNEZ": "COLEGIO",
    "GRANJA ALFREDO": "COMIDA",
    "MARKET CABILDO": "COMIDA",
    "MONOTR": "MONOTRIBUTO",
    "EDENOR": "EDENOR",
    "AREA FRESCA FOOD": "COMIDA",
    "PROP AMENABAR": "EXPENSAS",
    "SWISS MEDICAL": "REINTEGRO",
    "MERPAGO*LAPAZ": "COMIDA",
    "PANADERIA LA PAZ": "COMIDA",
    "CARREFOUR": "COMIDA",
    "MCDONALDS": "COMIDA",
    "WAISMAN": "OTROS",
    "ZITZER": "OTROS",
    "EL UNIVERSO DEL CONTRO": "OTROS",
    "CAROLINA ROCHA": "OTROS",
    "FARMACITY": "OTROS",
    "ALEJANDRO SAUL FAGUAGA": "OTROS",
    "LA VISION": "COMIDA",
    "Su Pago En Pesos": "PAGO TARJETA",
    "Hertz Car Rental": "OTROS",
    "Chase Center": "OTROS",
    "Golden State Warrior": "OTROS",
    "coto": "COMIDA",
    "Tuenti": "TELEFONIA",
    "potify": "ENTRETENIMIENTO",
    "Muni": "CLUB_CIUDAD_DE_BS_AS",
    "On Baires": "TAXI",
    "Duty Free": "OTROS",  # free shop aeropuerto
    "Walgreens": "COMIDA",
    "Miami Bch Prking-concn": "ESTACIONAMIENTO",  # estacionamiento publico en Miami
    "Doubletree Hotels": "HOTEL",
    "Tst* Italian Trattoria": "COMIDA",
    "Subway": "COMIDA",
    "Starbucks": "COMIDA",
    "Sq *boucher Brothers Miam": "OTROS",  # alquiler sombrilla en al playa Miami
    "Cvs/pharmacy": "COMIDA",
    "American Air": "OTROS",  # recargo por equipaje
    "Lyft *ride": "TAXI",
    "Riu Plaza": "HOTEL",
    "Grimoldi": "OTROS",
    "Farmacity": "OTROS",
    "Rappi": "COMIDA",
    "flybondi": "OTROS",
    "depilife": "OTROS",
    "Catedral Alta Patagon": "OTROS",
    "Vz Bath & Body": "OTROS",
    "Billabong": "OTROS",
    "Diseno Joven": "OTROS",
    "Rex": "OTROS",
    "Simmons": "OTROS",
    "La Valenziana": "OTROS",
    "Psadistribuidores": "OTROS",
    "saboresdelapa": "COMIDA",
    "Newbikes": "OTROS",
    "Divanes Saavedra": "OTROS",
    "multipointsa": "OTROS",
    "nuestrat": "OTROS",  # viaje de Bianca
    "Il Legno": "COMIDA",  # comida en aeropuerto
    "RENEDO, DEBORA": "OTROS",
    "BUFFETALBERTE": "COMIDA",
    "PESCADERIA BASILIO": "COMIDA",
    "MERCADOPAGO*LAPAZ": "COMIDA",
    "PIMPOLLO": "COMIDA",
    "NUEVA BELGRANO": "COMIDA",
    "DIA TIENDA": "COMIDA",
    "SUPERDIA": "COMIDA",
    "RES CAMPOS SALLES": "COMIDA",
    "A NANNI SILVANA": "OTROS",
    "GORRION": "COMIDA",
    "COTO DIGITAL": "COMIDA",
    "GRIDO": "COMIDA",
    "LA NUEVA BOMBON": "COMIDA",
    "PAGO DE TARJETA": "TARJETA",
    "DE GARCIA, JOAQUIN AUGUST": "JOAQUIN",
    "ESTEBAN MARIANO GRINBER": "OTROS",
    "SABORES COCINA PATAGON": "OTROS",
    "HOSPITAL DR ALBERTO DU": "OTROS",
    "YPF": "NAFTA",
    "TODO DULCE": "COMIDA",
    "GIGI & PAPPY": "COMIDA",
    "BURGER KING": "COMIDA",
    "CREMOLATTI": "COMIDA",
    "LEGADOMERCADO": "COMIDA",
    "VALERIA ANDREA CASANOVA": "OTROS",
    "VALERIA ALEJANDRA CACCH": "OTROS",
    "RETIRO DE EFECTIVO": "EFECTIVO",
    "CIUDAD HOCKEY": "OTROS",
    "YANG MINYING": "COMIDA",
    "FERNANDO CARLOS MATILLA": "OTROS",
    "MERPAGO*CARMIX": "OTROS",  # COMPRE BALDE PLEGABLE
    "LIBR*LAPAZ": "OTROS",
    "MERCADOPAGO*AGIPDGTESGCBA": "OTROS",  # REGISTRO
    "MERCADO LIBR*SOL": "OTROS",
    "LUMINARTE": "OTROS",
    "PAGO INTERES": "N/A",
    "TRASPASO DE SALDO": "N/A",
    "COBRO DE INTERES": "N/A",
    "TRANSFERENCIA NO GRAVADA           A OSCAR MARTIN PANIAGUA   / VARIOS       - VAR / 20240216559": "N/A",
    "TRANSFERENCIA RECIBIDA             DE PANIAGUA  OSCAR M": "N/A",
    "IVA 21": "N/A",
    "IMPUESTO LEY": "N/A",
    "IMPUESTO DE SELLOS": "N/A",
}
